---
- name: Deploy Cisco IOS-XE Router Configs
  connection: local
  hosts: cisco-ios-xe-routers
  gather_facts: no
  vars:
    creds:
        hostname: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        dev_os: "{{ device_type }}"
  tasks:
    - napalm_install_config:
        provider: "{{ creds }}"
        config_file: "configs/{{ inventory_hostname }}"
        commit_changes: True
        replace_config: False
      register: napalm_diff
    - debug:
        msg: "{{ item }}"
      with_items: "{{ napalm_diff.msg.split('\n') }}"

- name: Deploy Cisco NX-OS Configs
  connection: local
  hosts: cisco-nxos
  gather_facts: no
  vars:
    creds:
        hostname: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        dev_os: "{{ device_type }}"
  tags: nxos
  tasks:
    - napalm_install_config:
        provider: "{{ creds }}"
        config_file: "configs/{{ inventory_hostname }}"
        commit_changes: True
        replace_config: False
      register: napalm_diff
    - debug:
        msg: "{{ item }}"
      with_items: "{{ napalm_diff.msg.split('\n') }}"

- name: Deploy Cisco ASA Configs
  connection: local
  hosts: cisco-asa
  gather_facts: no
  vars:
    creds:
        host: "10.0.0.8"
        username: "{{ username }}"
        password: "{{ password }}"
        authorize: yes
        auth_pass: "{{ enable_password }}"
  tags: asa
  tasks:
    - asa_config:
        provider: "{{ creds }}"
        src: "configs/{{ inventory_hostname }}"
